[package]
name = "dsp-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "1", optional = true }
heapless = "0.8.0"
postcard-rpc = "0.11.13"
postcard-schema = { version = "0.2", features = ["derive"] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }

[features]
default = []

use-std = []
defmt = ["dep:defmt"]
