name: Rust build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: blus-dac
          submodules: true

      - name: Setup Rust Nightly
        run: |
          rustup toolchain install nightly -c rustfmt
          rustup target add thumbv8m.main-none-eabihf --toolchain nightly

      - name: Build STM32H5 (Force Nightly)
        run: |
          cd ./stm32h5
          cargo +nightly build --release
          
          # Указываем точное имя собранного файла из логов
          objcopy -O binary target/thumbv8m.main-none-eabihf/release/embassy-stm32h5-examples fw-stm32h5.bin
          cp fw-stm32h5.bin ../

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: stm32h5-firmware
          path: fw-stm32h5.bin
