name: Rust build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - run: rustup toolchain install nightly -c rustfmt

      - name: Install dependencies
        run: cargo install cargo-binutils

      - name: Build STM32H5
        run: |
          cd ./stm32h5
          cargo build --release
          cargo objcopy --release -- -O binary ../fw-stm32h5.bin

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: stm32h5-firmware
          path: fw-stm32h5.bin
