name: Rust build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - run: rustup toolchain install nightly -c rustfmt

      - name: Install dependencies
        run: cargo install cargo-binutils

      - name: Auto Find and Build STM32H5
        run: |
          # Ищем, где именно лежит папка проекта с STM32H5
          TARGET_DIR=$(find . -type d -name "*h5*" -not -path "*/target/*" | head -n 1)
          echo "Found project directory at: $TARGET_DIR"
          
          cd "$TARGET_DIR"
          cargo build --release
          
          # Превращаем скомпилированный elf-файл в прошивку .bin
          cargo objcopy --release -- -O binary fw-stm32h5.bin
          
          # Копируем её в корень для удобства скачивания
          cp fw-stm32h5.bin ../../

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: stm32h5-firmware
          path: fw-stm32h5.bin
